name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the contribution grid snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Shubh-Raj
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-light.svg?palette=github-light

      # Deploy to GitHub Pages
      - name: Deploy Snake Animation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
